### ISSUE TITLE
Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/HCC-Native-GCN-ISA#9]
Trying the saxyp example with hcc-lc gives the above error, but hsail seems to work.

Is the R390 supported by hcc?

I'm running the 1.2 kernel with most things installed

ls /opt/rocm/
bin  gdb  gpudebugsdk  hcc  hcc-hsail  hcc-lc  hip  hsa  include  lib  libamdgcn  libhsakmt  llvm  profiler

**Comment by gstoner** [comment]
We test the S9150 and W9100, the R390 is based on the same ASIC so it should just work also this GPU does not need Platform Atomics   HCC via HLC/HSAIL path work in 1.2

**Comment by Dekken** [comment]
Is there any documentation noting the ISA string per card, or are all Hawaii cards 7:0:1?

**Comment by Dekken** [comment]
Am I missing something [here](http://pastebin.com/raw/LYCMsNWC)?

What I get in the end is:
No suitable runtime detected. Fall back to CPU!
Segmentation fault

Can you imagine any issues running inside an LXC container?

**Comment by gstoner** [comment]
https://github.com/RadeonOpenCompute/ROCm-docker


How to build ROCm containers from source

While it is nice to quickly bring up a ROCm container from the latest apt-get release version, sometimes it is nice to be able to play with the latest development code. At the root of this repository is a bash script ./rocm-setup. It creates a set of Dockerfiles building the ROCm software components from source, with a yaml file used by docker-compose to manage the relationships between these containers.

Usage: ./rocm-setup [--master | --develop] [--release | --debug]
Default flags: --master --release

--master) Build dockerfiles from stable master branches; exclusive with --develop
--develop) Build dockerfiles from integration branches; exclusive with --master
--release) Build release containers; minimizes size of docker images; exclusive with --debug
--debug) Build debug containers; symbols generated and build tree intact for debugging; exclusive with --release

./rocm-setup generates Dockerfiles from textual template files ending with the .template suffix. Each sub-directory of this repository corresponds to a docker 'build context' responsible for a software layer in the ROCm stack. After running the script, each directory contains a generated 'Dockerfile'. The parameters to the script control the flavor of the components to build, for instance: debug builds of the /develop branches.

<https://github.com/RadeonOpenCompute/ROCm-docker#rocm-component-dictionary>ROCm component dictionary
ROC component
roct    the kernel thunk library
rocr    the runtime
hcc-hsail       the compiler that generates HSAIL IL from the backend
hcc-lc  the compiler that generates GPU ISA from the backend
<https://github.com/RadeonOpenCompute/ROCm-docker#what-git-branches-are-built-with-rocm-setup>What git branches are built with ./rocm-setup
        --master        --develop
roct    master  master
rocr    master  master
hcc-hsail       master  master
hcc-lc  clang_tot_upgrade       clang_tot_upgrade
<https://github.com/RadeonOpenCompute/ROCm-docker#when-building-rocm-components-from-source-we-are-locking-down-branches-to-known-good-configurations>When building ROCm components from source, we are locking down branches to known good configurations.
<https://github.com/RadeonOpenCompute/ROCm-docker#docker-compose>Docker compose

./rocm-setup prepares an environment that can be controlled with Docker Compose<https://docs.docker.com/compose/>. An output of the script is a docker-compose.yml file in the root of the repository, which coordinates the relationships between the various ROCm software layers. Additionally, the docker-compose.yml file can be extended to easily launch interactive application or development containers built on top of the ROCm software stack.

<https://github.com/RadeonOpenCompute/ROCm-docker#running-a-rocm-container-using-binaries-built-from-source>Running a ROCm container using binaries built from source

Using docker-compose, a target is provided that will import the data-only containers which build the individual ROCm components. If the images are not yet built, docker-compose will make sure to build them in the proper order. If they have already been built, it will re-use existing images.

  *   docker-compose run --rm rocm-from-src

<https://github.com/RadeonOpenCompute/ROCm-docker#creating-a-custom-applicationdevelopment-container>Creating a custom application/development container

The /rocm-terminal sub-directory contains a Dockerfile to build an image specifically built for ROCm software development. Useful development tools are pre-installed into the container, and it's meant to serve as a starting point for interested developers to customize a dockerfile for their own projects. To begin, simply: 1. copy the /rocm-terminal sub-directory into a new directory name, such as /my-rocm-terminal 2. open and customize the Dockerfile; pre-install dependencies and services 3. modify the docker-compose.yml.template file and add a new service which prepares a new image

  *   copy the 'rocm' target to build a container using the latest ROCm binary release
  *   copy the 'rocm-from-src' target to build a container using the latest ROCm source
     *   Run ./rocm-setup script to generate a new docker-compose.yml
     *   docker-compose run --rm <new-target-name>

For illustration, yaml source for an image that builds ROCm from source looks like

new-rocm-app:                         # docker-compose target name; was 'rocm-from-src'
  build:
    context: ./my-app                 # new directory used as build context
    dockerfile: Dockerfile
  devices:
    - "/dev/kfd"
  image: rocm/rocm-app               # the name of the generated docker image
  volumes:
    - ~:/usr/local/src/host-home     # add as many host directories to map into container as needed here
  volumes_from:                      # this section imports the binaries built from source
    - roct:ro
    - rocr:ro
    - hcc-lc:ro
    - hcc-hsail:ro

<https://github.com/RadeonOpenCompute/ROCm-docker#saving-work-in-a-container>Saving work in a container

Docker containers are typically ephemeral, and are discarded after closing the container with the '--rm' flag to docker run. However, there are times when it is desirable to close a container that has arbitrary work in it, and serialize it back into a docker image. This may be to to create a checkpoint in a long and complicated series of instructions, or it may be desired to share the image with others through a docker registry, such as docker hub.

sudo docker ps -a  # Find container of interest
sudo docker commit <container-name> <new-image-name>
sudo docker images # Confirm existence of a new image

<https://github.com/RadeonOpenCompute/ROCm-docker#rocm-user-has-root-privileges-by-default>rocm-user has root privileges by default

The dockerfile that serves as the 'terminal' creates a non-root user called rocm-user. Since this container is meant to serve as a development environment (and therefore apt-get likely needed), the user has been added to the linux sudo group. In addition, since it is somewhat difficult to set and change passwords in a container (often requiring a rebuild), the password prompt has been disabled for the sudo group. While this is convenient for development to be able sudo apt-get install packages, it does imply lower security in the container.

An option to increase container security:

  1.  Eliminate the sudo-nopasswd COPY statement in the dockerfile and replace with
  2.  Your own password with RUN echo 'account:password' | chpasswd

<https://github.com/RadeonOpenCompute/ROCm-docker#running-an-application-using-docker-compose>Running an application using docker-compose

You can run the new container (and its dependencies) with docker-compose.

docker-compose run --rm <my-rocm-terminal>  # run as rocm-user

Docker command reference
docker-compose  docker compose executable
run     sub-command to bring up interactive container
--rm    when shutting the container down, delete it
-u 0    override default user with root (uid 0)
my-rocm-terminal        application service defined in docker-compose.yml

To shut down ROCm dependencies and clean up

docker-compose down -v

Docker command reference
docker-compose  docker compose executable
down    sub-command to shut containers down and remove them
-v      clean-up shared volumes
<https://github.com/RadeonOpenCompute/ROCm-docker#footnotes>Footnotes:
[1] It can be installed into a container, it just doesn't do anything because containers do not go through the traditional boot process. We actually do provide a container for ROCK-Kernel-Driver, but it not used by the rest of the docker images. It does provide isolation and a reproducible environment for kernel development.
On Oct 29, 2016, at 7:30 AM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


Am I missing something here<http://pastebin.com/raw/LYCMsNWC>?

What I get in the end is:
No suitable runtime detected. Fall back to CPU!
Segmentation fault

Can you imagine any issues running inside an LXC container?

**Comment by Dekken** [comment]
https://github.com/lxcy/2.0.5-x86_64-debian8.6_hcc

**Comment by scchan** [comment]
Make sure you have access to /dev/kfd from within your container.  I've never use LXC.  With docker, a user would have to use either the --privileged or --device switch to enable access to kfd.  

I'd suggest you test with /opt/rocm/hsa/sample since it provides better low-level diagnostics

**Comment by Dekken** [comment]
Copying the compiled contents of the containers /opt/rocm to the host /opt/rocm and running the sample/vector under hsa did work, so there's probably something to your comment. More investigation required.

If I build [this](https://github.com/RadeonOpenCompute/HCC) it's the GCN version and not he HSAIL version?

**Comment by Dekken** [comment]
With the following lines in the LXC config I was able to get the hsa vector sample running

lxc.aa_allow_incomplete=1
lxc.autodev = 0
lxc.cgroup.devices.allow = c 244:0 rwm

the vector sample is not strictly a hcc sample, which is what I'm really trying to get working though.

**Comment by scchan** [comment]
The hsa vector sample verifies that the container has what it needs to access the GPU.
If your hcc example works outside the container, it should just work inside the container once device access has been granted.

**Comment by Dekken** [comment]
It works in neither environment sadly.

`./saxpy
No suitable runtime detected. Fall back to CPU!
Segmentation fault`

**Comment by Dekken** [comment]
Works in the container after adding "-Wl,--rpath=/opt/rocm/lib".

Which library does it need at runtime? "libhsa-runtime64.so"?

**Comment by scchan** [comment]
That's what I suspected... do an "ldd /opt/rocm/hcc-lc/lib/libmcwamp_hsa.so" to see the dependencies

**Comment by Dekken** [comment]
ldd /opt/rocm/hcc/lib/libmcwamp_hsa.so
        linux-vdso.so.1 (0x00007ffd0564e000)
        libhsa-runtime64.so.1 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f04e078d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f04e0481000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f04e0180000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f04dff6a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f04dfbbe000)
        /lib64/ld-linux-x86-64.so.2 (0x00005645be814000)

Strange that it doesn't complain on launch that it can't find "libhsa-runtime64.so" is it loaded with dlopen?

**Comment by scchan** [comment]
yes, with dlopen.  So did you install the runtime through the deb package?  It should have added a conf file to /etc/ld.so.conf.d so that loader could find it.

**Comment by Dekken** [comment]
No I built everything from source.

[Here's the script](http://pastebin.com/raw/LYCMsNWC)

**Comment by Dekken** [comment]
That script had a few typos as I was writing it while building all the parts by hand, [this script]() is better.
